apisix:
  node_listen: {{ .NodeListen }}
  enable_admin: false
  ssl:
    enable: false
    listen_port: {{ .SSLPort }}
nginx_config:                     # config for render the template to generate nginx.conf
  main_configuration_snippet: |
    daemon off;
  http_configuration_snippet: |
    server {
          access_log off;
          listen 9081 reuseport;
          location / {
              proxy_http_version 1.1;
              proxy_set_header Connection "";
              proxy_set_header Host $http_host;
              proxy_pass http://$connection_original_dst;
          }
    }
etcd:
  host:
    - "http://{{ .GRPCListen }}"     # multiple etcd address, if your etcd cluster enables TLS, please use https scheme,
    # e.g. "https://127.0.0.1:2379".
  prefix: "{{ .EtcdKeyPrefix }}"               # apisix configurations prefix
