// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base.proto

package apisix

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/envoyproxy/protoc-gen-validate/validate"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ID used to identify resources like Route, Upstream.
type ID struct {
	// Types that are valid to be assigned to OneofId:
	//	*ID_IntVal
	//	*ID_StrVal
	OneofId              isID_OneofId `protobuf_oneof:"oneof_id"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_6333a2c4f4076aaa, []int{0}
}
func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (dst *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(dst, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

type isID_OneofId interface {
	isID_OneofId()
}

type ID_IntVal struct {
	IntVal int64 `protobuf:"varint,1,opt,name=int_val,json=intVal,proto3,oneof"`
}

type ID_StrVal struct {
	StrVal string `protobuf:"bytes,2,opt,name=str_val,json=strVal,proto3,oneof"`
}

func (*ID_IntVal) isID_OneofId() {}

func (*ID_StrVal) isID_OneofId() {}

func (m *ID) GetOneofId() isID_OneofId {
	if m != nil {
		return m.OneofId
	}
	return nil
}

func (m *ID) GetIntVal() int64 {
	if x, ok := m.GetOneofId().(*ID_IntVal); ok {
		return x.IntVal
	}
	return 0
}

func (m *ID) GetStrVal() string {
	if x, ok := m.GetOneofId().(*ID_StrVal); ok {
		return x.StrVal
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ID) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ID_OneofMarshaler, _ID_OneofUnmarshaler, _ID_OneofSizer, []interface{}{
		(*ID_IntVal)(nil),
		(*ID_StrVal)(nil),
	}
}

func _ID_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ID)
	// oneof_id
	switch x := m.OneofId.(type) {
	case *ID_IntVal:
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.IntVal))
	case *ID_StrVal:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.StrVal)
	case nil:
	default:
		return fmt.Errorf("ID.OneofId has unexpected type %T", x)
	}
	return nil
}

func _ID_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ID)
	switch tag {
	case 1: // oneof_id.int_val
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.OneofId = &ID_IntVal{int64(x)}
		return true, err
	case 2: // oneof_id.str_val
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.OneofId = &ID_StrVal{x}
		return true, err
	default:
		return false, nil
	}
}

func _ID_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ID)
	// oneof_id
	switch x := m.OneofId.(type) {
	case *ID_IntVal:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.IntVal))
	case *ID_StrVal:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.StrVal)))
		n += len(x.StrVal)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*ID)(nil), "ID")
}

func init() { proto.RegisterFile("base.proto", fileDescriptor_base_6333a2c4f4076aaa) }

var fileDescriptor_base_6333a2c4f4076aaa = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4a, 0x2c, 0x4e,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0x12, 0x2f, 0x4b, 0xcc, 0xc9, 0x4c, 0x49, 0x2c, 0x49,
	0xd5, 0x87, 0x31, 0x20, 0x12, 0x4a, 0xb9, 0x5c, 0x4c, 0x9e, 0x2e, 0x42, 0x4a, 0x5c, 0xec, 0x99,
	0x79, 0x25, 0xf1, 0x65, 0x89, 0x39, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xcc, 0x4e, 0xec, 0xbf, 0x9c,
	0x58, 0x94, 0x98, 0x34, 0x18, 0x3d, 0x18, 0x82, 0xd8, 0x32, 0xf3, 0x4a, 0xc2, 0x12, 0x73, 0x84,
	0xcc, 0xb9, 0xd8, 0x8b, 0x4b, 0x8a, 0xc0, 0x6a, 0x98, 0x14, 0x18, 0x35, 0x38, 0x9d, 0x64, 0x7e,
	0x39, 0x49, 0x16, 0x89, 0x0b, 0x30, 0x4a, 0x38, 0x18, 0x09, 0xc6, 0x45, 0x27, 0xea, 0x56, 0x39,
	0xea, 0x46, 0x19, 0xe8, 0x5a, 0xea, 0xc6, 0xeb, 0xc5, 0x6a, 0xab, 0x80, 0x34, 0x16, 0x97, 0x14,
	0x85, 0x25, 0xe6, 0x38, 0x71, 0x71, 0x71, 0xe4, 0xe7, 0xa5, 0xe6, 0xa7, 0xc5, 0x67, 0xa6, 0x38,
	0x71, 0x44, 0xb1, 0x25, 0x16, 0x64, 0x16, 0x67, 0x56, 0x24, 0xb1, 0x81, 0xed, 0x37, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x9a, 0x0d, 0x9d, 0xd9, 0xa6, 0x00, 0x00, 0x00,
}
