// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: route.proto

package apisix

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on Route with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Route) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Route with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in RouteMultiError, or nil if none found.
func (m *Route) ValidateAll() error {
	return m.validate(true)
}

func (m *Route) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetUris()) < 1 {
		err := RouteValidationError{
			field:  "Uris",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	_Route_Uris_Unique := make(map[string]struct{}, len(m.GetUris()))

	for idx, item := range m.GetUris() {
		_, _ = idx, item

		if _, exists := _Route_Uris_Unique[item]; exists {
			err := RouteValidationError{
				field:  fmt.Sprintf("Uris[%v]", idx),
				reason: "repeated value must contain unique items",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {
			_Route_Uris_Unique[item] = struct{}{}
		}

		// no validation rules for Uris[idx]
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 100 {
		err := RouteValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 100 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Id

	if utf8.RuneCountInString(m.GetDesc()) > 256 {
		err := RouteValidationError{
			field:  "Desc",
			reason: "value length must be at most 256 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Priority

	_Route_Methods_Unique := make(map[string]struct{}, len(m.GetMethods()))

	for idx, item := range m.GetMethods() {
		_, _ = idx, item

		if _, exists := _Route_Methods_Unique[item]; exists {
			err := RouteValidationError{
				field:  fmt.Sprintf("Methods[%v]", idx),
				reason: "repeated value must contain unique items",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {
			_Route_Methods_Unique[item] = struct{}{}
		}

		if _, ok := _Route_Methods_InLookup[item]; !ok {
			err := RouteValidationError{
				field:  fmt.Sprintf("Methods[%v]", idx),
				reason: "value must be in list [GET POST PUT DELETE PATCH HEAD OPTIONS CONNECT TRACE]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(m.GetHosts()) > 0 {

		if len(m.GetHosts()) < 1 {
			err := RouteValidationError{
				field:  "Hosts",
				reason: "value must contain at least 1 item(s)",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		_Route_Hosts_Unique := make(map[string]struct{}, len(m.GetHosts()))

		for idx, item := range m.GetHosts() {
			_, _ = idx, item

			if _, exists := _Route_Hosts_Unique[item]; exists {
				err := RouteValidationError{
					field:  fmt.Sprintf("Hosts[%v]", idx),
					reason: "repeated value must contain unique items",
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			} else {
				_Route_Hosts_Unique[item] = struct{}{}
			}

			if !_Route_Hosts_Pattern.MatchString(item) {
				err := RouteValidationError{
					field:  fmt.Sprintf("Hosts[%v]", idx),
					reason: "value does not match regex pattern \"^\\\\*?[0-9a-zA-Z-._]+$\"",
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}

	}

	if len(m.GetRemoteAddrs()) > 0 {

		if len(m.GetRemoteAddrs()) < 1 {
			err := RouteValidationError{
				field:  "RemoteAddrs",
				reason: "value must contain at least 1 item(s)",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		_Route_RemoteAddrs_Unique := make(map[string]struct{}, len(m.GetRemoteAddrs()))

		for idx, item := range m.GetRemoteAddrs() {
			_, _ = idx, item

			if _, exists := _Route_RemoteAddrs_Unique[item]; exists {
				err := RouteValidationError{
					field:  fmt.Sprintf("RemoteAddrs[%v]", idx),
					reason: "repeated value must contain unique items",
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			} else {
				_Route_RemoteAddrs_Unique[item] = struct{}{}
			}

			// no validation rules for RemoteAddrs[idx]
		}

	}

	for idx, item := range m.GetVars() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RouteValidationError{
						field:  fmt.Sprintf("Vars[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RouteValidationError{
						field:  fmt.Sprintf("Vars[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RouteValidationError{
					field:  fmt.Sprintf("Vars[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPlugins()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RouteValidationError{
					field:  "Plugins",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RouteValidationError{
					field:  "Plugins",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPlugins()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RouteValidationError{
				field:  "Plugins",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for ServiceId

	// no validation rules for UpstreamId

	// no validation rules for Status

	if len(errors) > 0 {
		return RouteMultiError(errors)
	}
	return nil
}

// RouteMultiError is an error wrapping multiple validation errors returned by
// Route.ValidateAll() if the designated constraints aren't met.
type RouteMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RouteMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RouteMultiError) AllErrors() []error { return m }

// RouteValidationError is the validation error returned by Route.Validate if
// the designated constraints aren't met.
type RouteValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RouteValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RouteValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RouteValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RouteValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RouteValidationError) ErrorName() string { return "RouteValidationError" }

// Error satisfies the builtin error interface
func (e RouteValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRoute.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RouteValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RouteValidationError{}

var _Route_Methods_InLookup = map[string]struct{}{
	"GET":     {},
	"POST":    {},
	"PUT":     {},
	"DELETE":  {},
	"PATCH":   {},
	"HEAD":    {},
	"OPTIONS": {},
	"CONNECT": {},
	"TRACE":   {},
}

var _Route_Hosts_Pattern = regexp.MustCompile("^\\*?[0-9a-zA-Z-._]+$")
