metadata:
  labels:
    service.istio.io/canonical-name: {{ index .ObjectMeta.Labels `service.istio.io/canonical-name` | default (index .ObjectMeta.Labels `app.kubernetes.io/name`) | default (index .ObjectMeta.Labels `app`) | default .DeploymentMeta.Name  | quote }}
    service.istio.io/canonical-revision: {{ index .ObjectMeta.Labels `service.istio.io/canonical-revision` | default (index .ObjectMeta.Labels `app.kubernetes.io/version`) | default (index .ObjectMeta.Labels `version`) | default "latest"  | quote }}
    istio.io/rev: {{ .Revision | default "default" | quote }}
spec:
  initContainers:
  - name: istio-init
    image: "{{ .Values.global.proxy_init.hub }}/{{ .Values.global.proxy_init.image }}:{{ .Values.global.proxy_init.tag }}"
    args:
    - iptables
    - --apisix-user
    - nobody
    - --apisix-inbound-capture-port
    - "9081"
    - --apisix-port
    - "9080"
    - --inbound-ports
    - "*"
    - --inbound-exclude-ports
    - "17739"
    - --outbound-ports
    - "*"
    - --outbound-exclude-ports
    - "17739,15010"
    imagePullPolicy: "{{ valueOrDefault .Values.global.imagePullPolicy `Always` }}"
    securityContext:
      allowPrivilegeEscalation: {{ .Values.global.proxy.privileged }}
      privileged: {{ .Values.global.proxy.privileged }}
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        drop:
        - ALL
      readOnlyRootFilesystem: false
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
    restartPolicy: Always
  containers:
  - name: istio-proxy
    image: "{{ .Values.global.proxy.hub }}/{{ .Values.global.proxy.image }}:{{ .Values.global.proxy.tag }}"
    ports:
    - containerPort: 9080
      protocol: TCP
      name: http-outbound
    - containerPort: 9081
      protocol: TCP
      name: http-inbound
    - containerPort: 17739
      protocol: TCP
      name: agent
    args:
    - sidecar
    - --run-mode
    - bundle
    - --provisioner
    - xds-v3-grpc
    - --log-level
    - debug
    - --xds-config-source
    - "grpc://istiod.{{ .Values.global.istioNamespace }}.svc.{{ .Values.global.proxy.clusterDomain }}:15010"
    - --apisix-bin-path
    - /usr/bin/apisix
    - --grpc-listen
    - 0.0.0.0:17739
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    imagePullPolicy: "{{ valueOrDefault .Values.global.imagePullPolicy `Always` }}"
