name: e2e-test-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.10.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv kind /usr/local/bin
      - name: Setup Go Environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.16.5'
      - name: Install ginkgo
        run: |
          go get -u github.com/onsi/ginkgo/ginkgo
          sudo cp ~/go/bin/ginkgo /usr/local/bin
      - name: Run e2e test cases
        env:
          GITHUB_ACTIONS: true
        working-directory: ./
        run: |
          cd e2e && go mod download && cd ..
          make e2e-test E2E_CONCURRENCY=1
      - name: upload coverage profile
        working-directory: ./e2e
        run: |
          bash <(curl -s https://codecov.io/bash)
