name: License Checker

on:
  push:
    branches:
      - master
  pull_request: null
jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run License Checker
        run: |
          make license-check
