name: Unit Test Suites

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go Environment
      uses: actions/setup-go@v1
      with:
        go-version: '1.16'
    - name: Run Unit Test Suites
      working-directory: ./
      run: |
        make unit-test
    - name: Upload Coverage Profile
      working-directory: ./
      run: |
        bash <(curl -s https://codecov.io/bash) -t 615ec963-1638-4ca8-956c-7e33be81fd44
